core/urls.py
from django.urls import path
from .views import UserListView, AddUserView, ProfileView, avatar_add
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('users/', UserListView.as_view(), name='user_list'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('users/add/', AddUserView.as_view(), name='add_user'),
    path('users/profile/', ProfileView.as_view(), name='profile'),
    path('users/profile/<int:user>/', ProfileView.as_view(), name='other_profile'),
    path('users/profile/avatar/add/', avatar_add, name='avatar_add'),
]

timetracking/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('users/', include('core.urls')),
    path('projects/', include('projects.urls')),
    path('tasks/', include('tasks.urls')),
    path('timelogs/', include('timelogs.urls')),
]

projects/models.py
from django.db import models
from core.models import AbstractRichTextModel
from django.urls import reverse_lazy


class Project(AbstractRichTextModel):

    def get_absolute_url(self):
        return reverse_lazy('project_detail', kwargs={'slug': self.slug})

tasks/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse_lazy
from django.utils import timezone

from core.models import AbstractRichTextModel
from core.utils import html_clean
from projects.models import Project


User = get_user_model()


class Task(AbstractRichTextModel):
    TYPE_CHOICES = (
        ('feature', 'Feature'),
        ('bug', 'Bug')
    )
    PRIORITY_CHOICES = (
        ('normal', 'Normal'),
        ('high', 'High'),
        ('urgent', 'Urgent')
    )
    STATUS_CHOICES = (
        ('new', 'New'),
        ('in_progress', 'In progress'),
        ('solved', 'Solved'),
        ('declined', 'Declined')
    )
    start_date = models.DateTimeField(null=True, blank=True)
    end_date = models.DateTimeField(null=True, blank=True)
    type = models.CharField(max_length=8, choices=TYPE_CHOICES)
    priority = models.CharField(max_length=8, choices=PRIORITY_CHOICES)
    estimate = models.PositiveIntegerField(default=0)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='tasks')
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True,
                                related_name='created_tasks')
    assigned_to = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='assigned_tasks',
                                    null=True, blank=True)
    status = models.CharField(max_length=12, choices=STATUS_CHOICES, default='new')
    closed = models.BooleanField(default=False, db_index=True)

    def get_absolute_url(self):
        return reverse_lazy('task_detail', kwargs={'slug': self.slug})

    def get_watchers(self):
        watchers = []
        if self.creator and self.creator.email:
            watchers.append(self.creator.email)
        if self.assigned_to and self.assigned_to.email:
            watchers.append(self.assigned_to.email)
        return list(set(watchers))

    def save(self, *args, **kwargs):
        if not self.start_date and self.status == 'in_progress':
            self.start_date = timezone.now()
        super(Task, self).save(*args, **kwargs)


class TaskComment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = RichTextField()
    comment_date = models.DateTimeField(auto_now_add=True)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='comments')

    def get_absolute_url(self):
        return self.task.get_absolute_url()

    def save(self, *args, **kwargs):
        self.comment = html_clean(self.comment)
        return super().save(*args, **kwargs)

    def __str__(self):
        return "%s %s" % (self.author.get_full_name(), self.comment_date.strftime("%Y-%m-%d"))

templates/base.html
{% load static %}
{% load avatar_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% if title %}{{ title }} — {% endif %}TimeTracking</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap4.3.1.min.css' %}">
    <script src="{% static 'js/jquery3.4.1.min.js' %}"></script>
    <script src="{% static 'js/popper1.14.7.min.js' %}"></script>
    <script src="{% static 'js/bootstrap4.3.1.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'jqueryui/jquery-ui.min.css' %}">
    <link rel="stylesheet" href="{% static 'jqueryui/jquery-ui.theme.min.css' %}">
    <script src="{% static 'jqueryui/jquery-ui.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="{% url 'home' %}">TimeTracking</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
  {% if user.is_authenticated %}
    <ul class="nav navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'project_list' %}">Projects</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'task_list' %}">Tasks</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'timelog' %}">Time log</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'user_list' %}">Users</a>
      </li>
{% endif %}
    </ul>
  <ul class="nav navbar-nav ml-auto">
  {% if user.is_authenticated %}
    <li class="nav-item">
        <a class="nav-link profile-link" href="{% url 'profile' %}">{% avatar user 30 class="img-circle img-responsive" id="user_avatar" %}</a>
    </li>
  {% endif %}
      <li class="nav-item">
          {% if user.is_authenticated %}

        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          {% else %}
        <a class="nav-link" href="{% url 'login' %}">Login</a>
          {% endif %}
      </li>
  </ul>
  </div>

</nav>
<div class="container" id="main-content">
{% block content %}
{% endblock %}
</div>
</body>
</html>