core/urls.py
from django.urls import path
from .views import UserListView, AddUserView, ProfileView, avatar_add
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('users/', UserListView.as_view(), name='user_list'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('users/add/', AddUserView.as_view(), name='add_user'),
    path('users/profile/', ProfileView.as_view(), name='profile'),
    path('users/profile/<int:user>/', ProfileView.as_view(), name='other_profile'),
    path('users/profile/avatar/add/', avatar_add, name='avatar_add'),
]

tasks/urls.py
from django.urls import path

from .views import CreateTaskView, TaskListView, UpdateTaskView, TaskDetailView, AddCommentView


urlpatterns = [
    path('tasks/', TaskListView.as_view(), name='task_list'),
    path('tasks/<slug:slug>/', TaskDetailView.as_view(), name='task_detail'),
    path('tasks/<int:task_pk>/comments/create/', AddCommentView.as_view(), name='add_comment'),
    path('tasks/edit/<slug:slug>/', UpdateTaskView.as_view(), name='edit_task'),
    path('tasks/<int:project_pk>/create/', CreateTaskView.as_view(), name='create_task'),
]

timelogs/urls.py
from django.urls import path
from .views import TimeLogView, DeleteLogView, LogTimeView


urlpatterns = [
    path('timelog/', TimeLogView.as_view(), name='timelog'),
    path('timelog/<int:pk>/', DeleteLogView.as_view(), name='timelog_delete'),
    path('timelog/create/<int:task_pk>/', LogTimeView.as_view(), name='log_time'),
]

timetracking/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('users/', include('core.urls')),
    path('projects/', include('projects.urls')),
    path('tasks/', include('tasks.urls')),
    path('timelogs/', include('timelogs.urls')),
]

tasks/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse_lazy
from django.utils import timezone

from core.models import AbstractRichTextModel
from core.utils import html_clean
from projects.models import Project


User = get_user_model()


class Task(AbstractRichTextModel):
    TYPE_CHOICES = (
        ('feature', 'Feature'),
        ('bug', 'Bug')
    )
    PRIORITY_CHOICES = (
        ('normal', 'Normal'),
        ('high', 'High'),
        ('urgent', 'Urgent')
    )
    STATUS_CHOICES = (
        ('new', 'New'),
        ('in_progress', 'In progress'),
        ('solved', 'Solved'),
        ('declined', 'Declined')
    )
    start_date = models.DateTimeField(null=True, blank=True)
    end_date = models.DateTimeField(null=True, blank=True)
    type = models.CharField(max_length=8, choices=TYPE_CHOICES)
    priority = models.CharField(max_length=8, choices=PRIORITY_CHOICES)
    estimate = models.PositiveIntegerField(default=0)
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='tasks')
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True,
                                related_name='created_tasks')
    assigned_to = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='assigned_tasks',
                                    null=True, blank=True)
    status = models.CharField(max_length=12, choices=STATUS_CHOICES, default='new')
    closed = models.BooleanField(default=False, db_index=True)

    def get_absolute_url(self):
        return reverse_lazy('task_detail', kwargs={'slug': self.slug})

    def get_watchers(self):
        watchers = []
        if self.creator and self.creator.email:
            watchers.append(self.creator.email)
        if self.assigned_to and self.assigned_to.email:
            watchers.append(self.assigned_to.email)
        return list(set(watchers))

    def save(self, *args, **kwargs):
        if not self.start_date and self.status == 'in_progress':
            self.start_date = timezone.now()
        super(Task, self).save(*args, **kwargs)


class TaskComment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = RichTextField()
    comment_date = models.DateTimeField(auto_now_add=True)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='comments')

    def get_absolute_url(self):
        return self.task.get_absolute_url()

    def save(self, *args, **kwargs):
        self.comment = html_clean(self.comment)
        return super().save(*args, **kwargs)

    def __str__(self):
        return "%s %s" % (self.author.get_full_name(), self.comment_date.strftime("%Y-%m-%d"))

timelogs/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone

from tasks.models import Task


User = get_user_model()


class TimeLog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    time = models.PositiveIntegerField(default=0)
    date = models.DateField(default=timezone.now)
    created_date = models.DateTimeField(auto_now_add=True)
    comment = models.CharField(max_length=255)
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='time_logs')

    def __str__(self):
        return "{} ({}hs.)".format(self.author, self.time)

tasks/forms.py
from django import forms

from core.forms import WatchModelForm
from .models import Project, Task, TaskComment


class TaskForm(WatchModelForm):
    class Meta:
        model = Task
        exclude = ('closed', 'creator', 'project')

    watch_fields = ('name', 'description', 'status',
                    'start_date', 'end_date', 'type', 'priority', 'estimate', 'creator', 'assigned_to', 'creator')

    def save(self, commit=True, request=None):
        if not self.instance.pk:
            self.instance.creator = request.user
        return super().save(commit, request)

    def get_subscribers(self):
        return self.instance.get_watchers()


class TaskCommentForm(WatchModelForm):
    class Meta:
        model = TaskComment
        fields = ('comment', )
    watch_fields = ('comment', )

    def get_subscribers(self):
        return self.instance.task.get_watchers()

timelogs/forms.py
from django.core.exceptions import ValidationError

from core.forms import WatchModelForm
from .models import TimeLog


class TimeLogForm(WatchModelForm):
    class Meta:
        model = TimeLog
        fields = ('time', 'date', 'comment')

    watch_fields = ('time', 'date', 'comment')

    def clean_time(self):
        if int(self.cleaned_data['time']) <= 0:
            raise ValidationError('Time must be greater then 0')
        return self.cleaned_data['time']

    def get_subscribers(self):
        return self.instance.task.get_watchers()

tasks/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum
from django.http import Http404
from django.http.response import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView

from core.mixins import StaffRequiredMixin
from timelogs.forms import TimeLogForm
from timelogs.models import TimeLog
from .forms import TaskForm, TaskCommentForm
from .models import Project, Task, TaskComment

User = get_user_model()


class CreateTaskView(StaffRequiredMixin, CreateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/form_page.html'

    def get_success_url(self):
        return reverse_lazy('project_detail', kwargs={'slug': self.object.project.slug})

    def form_valid(self, form):
        form.instance.project = get_object_or_404(Project, pk=self.kwargs['project_pk'])
        form.instance.author = self.request.user
        self.object = form.save(request=self.request)
        return HttpResponseRedirect(self.get_success_url())


class UpdateTaskView(LoginRequiredMixin, UpdateView):
    model = Task
    form_class = TaskForm
    template_name = 'tasks/form_page.html'

    def get_success_url(self):
        return reverse_lazy('project_detail', kwargs={'slug': self.object.project.slug})

    def form_valid(self, form):
        self.object = form.save(request=self.request)
        return HttpResponseRedirect(self.get_success_url())


class TaskListView(LoginRequiredMixin, ListView):
    template_name = 'tasks/task_list.html'
    paginate_by = 15

    def get_queryset(self):
        if self.request.user.is_staff:
            return Task.objects.all()
        else:
            return Task.objects.filter(assigned_to=self.request.user).order_by('-id')


class TaskDetailView(LoginRequiredMixin, DetailView):
    model = Task
    template_name = 'tasks/task_page.html'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if not self.request.user.is_staff and obj.assigned_to != self.request.user:
            raise Http404
        return obj

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['comment_form'] = TaskCommentForm
        context['log_form'] = TimeLogForm
        context['spent_time'] = TimeLog.objects.filter(task=self.object).aggregate(sum=Sum('time'))['sum'] or 0
        return context


class AddCommentView(LoginRequiredMixin, CreateView):
    form_class = TaskCommentForm
    template_name = 'tasks/form_page.html'
    model = TaskComment

    def get_success_url(self):
        return reverse_lazy('task_detail', kwargs={'slug': self.object.task.slug})

    def form_valid(self, form):
        form.instance.task = get_object_or_404(Task, pk=self.kwargs['task_pk'])
        form.instance.author = self.request.user
        self.object = form.save(request=self.request)
        if self.request.is_ajax():
            comment = render_to_string('tasks/parts/comment.html', context={'comment': self.object})
            return JsonResponse({'html': comment, 'id': self.object.pk})
        return HttpResponseRedirect(self.get_success_url())

timelogs/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http.response import HttpResponseRedirect, JsonResponse
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DeleteView

from core.mixins import StaffRequiredMixin
from tasks.models import Task
from .forms import TimeLogForm
from .models import TimeLog


class LogTimeView(LoginRequiredMixin, CreateView):
    model = TimeLog
    form_class = TimeLogForm

    def dispatch(self, request, *args, **kwargs):
        returned = super().dispatch(request, *args, **kwargs)
        if self.object and self.object.task.assigned_to != request.user and not request.user.is_staff:
            return self.handle_no_permission()
        return returned

    def get_success_url(self):
        return reverse_lazy('task_detail', kwargs={'slug': self.object.task.slug})

    def form_valid(self, form):
        form.instance.task = get_object_or_404(Task, pk=self.kwargs['task_pk'])
        form.instance.author = self.request.user
        self.object = form.save(request=self.request)
        if self.request.is_ajax():
            comment = render_to_string('tasks/parts/log.html', context={'log': self.object})
            return JsonResponse({'html': comment, 'id': self.object.pk})
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form):
        if self.request.is_ajax:
            return JsonResponse({'errors': form.errors}, status=400)
        return super().form_invalid(form)


class TimeLogView(LoginRequiredMixin, ListView):
    template_name = 'tasks/timelog.html'
    paginate_by = 15

    def get_queryset(self):
        if self.request.user.is_staff:
            return TimeLog.objects.all()
        else:
            return TimeLog.objects.filter(task__assigned_to=self.request.user)


class DeleteLogView(StaffRequiredMixin, DeleteView):
    model = TimeLog
    success_url = reverse_lazy('timelog')

templates/tasks/form_page.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% block content %}
    <div class="container">
    <div class="row">
        <form method="post">
        {% csrf_token %}
            {{ form|crispy }}
        <input class="btn btn-primary" type="submit" value="Save">
        </form>
    {{ form.media }}
    </div>
    </div>
{% endblock %}

templates/tasks/profile.html
{% extends 'base.html' %}
{% load bootstrap_pagination %}
{% load crispy_forms_filters %}
{% load avatar_tags %}
{% block content %}
    <div class="container">
    <div class="row">
        <div class="col-md-6">
            <h4>Profile Settings</h4>
        <form action="" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input type="submit" class="btn btn-primary">
        </form>
        </div>
        {% if avatar_form %}
        <div class="col-md-6">
        <h4>Avatar</h4>
        {% avatar object 80 %}
        <form enctype="multipart/form-data" method="POST" action="{% url 'avatar_add' %}">
            {% csrf_token %}
            {{ avatar_form|crispy }}
            <input type="submit" class="btn btn-primary" value="Change">
        </form>
        </div>
        {% endif %}
    </div>
    </div>
{% endblock %}

templates/tasks/project_list.html
{% extends 'base.html' %}
{% block content %}
    <h2>Project list</h2>
    {% if user.is_staff %}
        <a href="{% url 'create_project' %}" class="btn btn-primary create-button">Create project</a>
    {% endif %}
    <ul class="list-group">
    {% for object in object_list %}
        <li class="mb-1 list-group-item list-group-item-action">
            <div class="d-flex w-100 justify-content-between">
              <h4><a href="{{ object.get_absolute_url }}" >{{ object.name }}</a></h4>
              <small>Created: {{ object.created_date|date:"Y-m-d H:i" }}</small>
            </div>
        <p>{{ object.description|safe }}</p>
        </li>
    {% endfor %}
    </ul>
{% endblock %}

templates/tasks/project_page.html
{% extends 'base.html' %}
{% block content %}
    <div class="d-flex justify-content-between">
        <h3>{{ object.name }}</h3>
        {% if user.is_staff %}
        <a href="{% url 'update_project' slug=object.slug %}">Edit</a>
        {% endif %}
    </div>
    <p>{{ object.description|safe }}</p>
    {% if user.is_staff %}
    <a href="{% url 'create_task' project_pk=object.pk %}" class="btn btn-primary create-button">Create task</a>
    {% endif %}
    <h4>Tasks</h4>

    {% include 'tasks/parts/task_list.html' with tasks=tasks %}
{% endblock %}

templates/tasks/task_list.html
{% extends 'base.html' %}
{% block content %}
    <h2>{% if user.is_staff %}All tasks{% else %}Tasks assigned to you{% endif %}</h2>
{% include 'tasks/parts/task_list.html' with tasks=object_list %}
{% endblock %}

templates/tasks/task_page.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load avatar_tags %}
{% block content %}
    <div class="container">
    <div class="d-flex justify-content-between">
        <h3>{{ object.name }}</h3>
        <a href="{% url 'edit_task' slug=object.slug %}">Edit</a>
    </div>
    <div class="row task-info">
        <div class="col-md-4"><span>Project:</span> <a href="{{ object.project.get_absolute_url }}"></a>{{ object.project }}</div>
        <div class="col-md-4"><span>Status:</span> {{ object.get_status_display }}</div>
        <div class="col-md-4"><span>Type:</span> {{ object.get_type_display }}</div>
        <div class="col-md-4"><span>Created:</span> {% avatar object.creator 20 class="img-circle img-responsive comment-avatar" %} {{ object.creator.get_full_name }} {{ object.created_date|date:"Y-m-d H:i:s" }}</div>
        <div class="col-md-4"><span>Assigned to:</span>{% if object.assigned_to %} {% avatar object.assigned_to 20 class="img-circle img-responsive comment-avatar" %}{% endif %} {{ object.assigned_to.get_full_name|default_if_none:"-" }}</div>
        <div class="col-md-4"><span>Spent time:</span> {{ spent_time }}hr{{ spent_time|pluralize }}.</div>
    </div>
    <div class="task-description">
        <p>{{ object.description|safe }}</p>
    </div>
    <div class="task-tracked-time">
        <div class="d-flex justify-content-between">
        <h5>Logged time</h5>
        {% if object.assigned_to == user or user.is_staff %}
            <a href="#" data-toggle="modal" data-target="#exampleModal">Log time</a>
        {% endif %}
        </div>

        <div class="table-responsive">
            <table class="table time-log">
                <thead>
                <tr>
                    <th>User</th>
                    <th>Time</th>
                    <th>Comment</th>
                    <th>Date</th>
                    <th>Log created</th>
                </tr>
                </thead>
                <tbody>
                {% for log in object.time_logs.all %}
                <tr>
                    <td>{{ log.author }}</td>
                    <td>{{ log.time }}hr{{ log.time|pluralize }}</td>
                    <td>{{ log.comment }}</td>
                    <td>{{ log.date }}</td>
                    <td>{{ log.created_date }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
        <hr>
        <h5>Comments</h5>
        {% for comment in object.comments.all %}
            {% include 'tasks/parts/comment.html' %}
        {% endfor %}
    <div class="">
        <form action="{% url 'add_comment' task_pk=object.pk %}" id="add-comment" method="post">
        <h5>Add comment</h5>
        {% csrf_token %}
        {{ comment_form|crispy }}
        <input type="submit" value="Add comment" class="btn btn-primary">
        </form>
        {{ comment_form.media }}
    </div>
    </div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Log Time</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{% url 'log_time' task_pk=object.pk %}" method="post" id="add-log-form">
              <div class="alert-danger alert d-none" id="log-form-errors"></div>
              {% csrf_token %}
              {{ log_form|crispy }}
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="submit-log">Log time</button>
      </div>
    </div>
  </div>
</div>

{% endblock %}

templates/tasks/timelog.html
{% extends 'base.html' %}
{% load bootstrap_pagination %}
{% block content %}
    <h2>Time log</h2>
<div class="table-responsive">
    <table class="table time-log">
        <thead>
        <tr>
            <th>User</th>
            <th>Task</th>
            <th>Time</th>
            <th>Comment</th>
            <th>Date</th>
            <th>Log created</th>
            {% if user.is_staff %}<th></th>{% endif %}
        </tr>
        </thead>
        <tbody>
        {% for log in object_list %}
        <tr data-id="{{ log.id }}">
            <td>{{ log.author.get_full_name }}</td>
            <td><a href="{{ log.task.get_absolute_url }}">{{ log.task.name }} (#{{ log.task.pk }})</a></td>
            <td>{{ log.time }}hr{{ log.time|pluralize }}</td>
            <td>{{ log.comment }}</td>
            <td>{{ log.date }}</td>
            <td>{{ log.created_date }}</td>
            {% if user.is_staff %}<td><a href="{% url 'timelog_delete' pk=log.pk %}" class="remove-log">x</a></td>{% endif %}
        </tr>
        {% endfor %}
        </tbody>
    </table>
{% bootstrap_paginate page_obj %}
</div>
{% if user.is_staff %}
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          {% csrf_token %}
        <h4>Are you sure to remove this log?</h4>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="remove-log-modal">Yes</button>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}

templates/tasks/timelog_confirm_delete.html
{% extends 'base.html' %}
{% block content %}
    <div class="container">
    <div class="alert alert-danger d-flex justify-content-between">
        <h5>A you sure want to delete this timelog?</h5>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger">
    </form>
    </div>
    </div>
{% endblock %}

templates/tasks/users.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <h2>Users</h2>
    {% if user.is_staff %}
    <a href="{% url 'add_user' %}" class="btn btn-primary create-button">Add user</a>
    {% endif %}
    <div class="table-responsive">
        <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Username</th>
                <th scope="col">Email</th>
                <th scope="col">Full Name</th>
                <th scope="col">Admin?</th>
                <th scope="col">Position</th>
                <th scope="col">Birthday</th>
                {% if user.is_staff %}<th scope="col">Last login</th>{% endif %}
            </tr>
        </thead>
        <tbody>
    {% for object in object_list %}
        <tr>
            <td>{% if user.is_staff %}<a href="{% url 'other_profile' user=object.id %}">{{ object.pk }}</a>{% else %}{{ object.pk }}{% endif %}</td>
            <td>{{ object.username }}</td>
            <td>{{ object.email }}</td>
            <td>{{ object.get_full_name }}</td>
            <td>{% if object.is_staff %}<img src="{% static 'admin/img/icon-yes.svg' %}" alt="Yes">{% endif %}</td>
            <td>{{ object.position|default_if_none:"" }}</td>
            <td>{{ object.birhday }}</td>
            {% if user.is_staff %}<td>{{ object.last_login|default_if_none:"" }}</td>{% endif %}
        </tr>
    {% endfor %}
        </tbody>
        </table>
    </div>
{% endblock %}